### ISSUE TITLE
Ottimo

### ISSUE THREAD

**Issue by sdoro** [LeonardoChirivi/Sorting-Algorithms#1]
Good job! Continue

**Comment by LeonardoChirivi** [comment]
thank you!

**Comment by sdoro** [comment]
Now test a branch! For example make a branch where you accept from input the size of array. Try it please

**Comment by LeonardoChirivi** [comment]
Done! I've made a branch named arraySize where you can get user's input!

**Comment by sdoro** [comment]
Now close this issue :)
