### ISSUE TITLE
Why merge ?

### ISSUE THREAD

**Issue by sdoro** [LeonardoChirivi/Sorting-Algorithms#2]
In the commit history sometime there are "Merge [...]" message. Why ?
![git](https://cloud.githubusercontent.com/assets/1675491/11813636/d7fb2fe4-a342-11e5-8b64-ffd0b5dd37da.png)

**Comment by LeonardoChirivi** [comment]
![merge](https://cloud.githubusercontent.com/assets/11871156/11813787/7596ba70-a343-11e5-8149-fbcc72c2aa38.png)

**Comment by LeonardoChirivi** [comment]
because i've modified the README.md file on github, and I had to pull from remote in order to be to push  new commits.
I think it's a conflict problem or whatever when you modifify files in remote.

**Comment by sdoro** [comment]
Yes, may be. But you must avoid to conflict with yourself! What do you think to do to avoid this particular type of conflict ?

**Comment by LeonardoChirivi** [comment]
$~ git pull
$~ git push

**Comment by LeonardoChirivi** [comment]
That's how i solved!

**Comment by sdoro** [comment]
I hope!
